
# 21 "/usr/include/GLES2/gl2platform.h" 2 3 4
# 7 "/usr/include/GLES2/gl2.h" 2
# 21 "/usr/include/GLES2/gl2.h"
typedef void GLvoid;
typedef char GLchar;
typedef unsigned int GLenum;
typedef unsigned char GLboolean;
typedef unsigned int GLbitfield;
typedef khronos_int8_t GLbyte;
typedef short GLshort;
typedef int GLint;
typedef int GLsizei;
typedef khronos_uint8_t GLubyte;
typedef unsigned short GLushort;
typedef unsigned int GLuint;
typedef khronos_float_t GLfloat;
typedef khronos_float_t GLclampf;
typedef khronos_int32_t GLfixed;


typedef khronos_intptr_t GLintptr;
typedef khronos_ssize_t GLsizeiptr;
# 474 "/usr/include/GLES2/gl2.h"
 void glActiveTexture (GLenum texture);
 void glAttachShader (GLuint program, GLuint shader);
 void glBindAttribLocation (GLuint program, GLuint index, const GLchar* name);
 void glBindBuffer (GLenum target, GLuint buffer);
 void glBindFramebuffer (GLenum target, GLuint framebuffer);
 void glBindRenderbuffer (GLenum target, GLuint renderbuffer);
 void glBindTexture (GLenum target, GLuint texture);
 void glBlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
 void glBlendEquation ( GLenum mode );
 void glBlendEquationSeparate (GLenum modeRGB, GLenum modeAlpha);
 void glBlendFunc (GLenum sfactor, GLenum dfactor);
 void glBlendFuncSeparate (GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
 void glBufferData (GLenum target, GLsizeiptr size, const GLvoid* data, GLenum usage);
 void glBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid* data);
 GLenum glCheckFramebufferStatus (GLenum target);
 void glClear (GLbitfield mask);
 void glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
 void glClearDepthf (GLclampf depth);
 void glClearStencil (GLint s);
 void glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
 void glCompileShader (GLuint shader);
 void glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid* data);
 void glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid* data);
 void glCopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
 void glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
 GLuint glCreateProgram (void);
 GLuint glCreateShader (GLenum type);
 void glCullFace (GLenum mode);
 void glDeleteBuffers (GLsizei n, const GLuint* buffers);
 void glDeleteFramebuffers (GLsizei n, const GLuint* framebuffers);
 void glDeleteProgram (GLuint program);
 void glDeleteRenderbuffers (GLsizei n, const GLuint* renderbuffers);
 void glDeleteShader (GLuint shader);
 void glDeleteTextures (GLsizei n, const GLuint* textures);
 void glDepthFunc (GLenum func);
 void glDepthMask (GLboolean flag);
 void glDepthRangef (GLclampf zNear, GLclampf zFar);
 void glDetachShader (GLuint program, GLuint shader);
 void glDisable (GLenum cap);
 void glDisableVertexAttribArray (GLuint index);
 void glDrawArrays (GLenum mode, GLint first, GLsizei count);
 void glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid* indices);
 void glEnable (GLenum cap);
 void glEnableVertexAttribArray (GLuint index);
 void glFinish (void);
 void glFlush (void);
 void glFramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
 void glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
 void glFrontFace (GLenum mode);
 void glGenBuffers (GLsizei n, GLuint* buffers);
 void glGenerateMipmap (GLenum target);
 void glGenFramebuffers (GLsizei n, GLuint* framebuffers);
 void glGenRenderbuffers (GLsizei n, GLuint* renderbuffers);
 void glGenTextures (GLsizei n, GLuint* textures);
 void glGetActiveAttrib (GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
 void glGetActiveUniform (GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
 void glGetAttachedShaders (GLuint program, GLsizei maxcount, GLsizei* count, GLuint* shaders);
 int glGetAttribLocation (GLuint program, const GLchar* name);
 void glGetBooleanv (GLenum pname, GLboolean* params);
 void glGetBufferParameteriv (GLenum target, GLenum pname, GLint* params);
 GLenum glGetError (void);
 void glGetFloatv (GLenum pname, GLfloat* params);
 void glGetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint* params);
 void glGetIntegerv (GLenum pname, GLint* params);
 void glGetProgramiv (GLuint program, GLenum pname, GLint* params);
 void glGetProgramInfoLog (GLuint program, GLsizei bufsize, GLsizei* length, GLchar* infolog);
 void glGetRenderbufferParameteriv (GLenum target, GLenum pname, GLint* params);
 void glGetShaderiv (GLuint shader, GLenum pname, GLint* params);
 void glGetShaderInfoLog (GLuint shader, GLsizei bufsize, GLsizei* length, GLchar* infolog);
 void glGetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision);
 void glGetShaderSource (GLuint shader, GLsizei bufsize, GLsizei* length, GLchar* source);
 const GLubyte* glGetString (GLenum name);
 void glGetTexParameterfv (GLenum target, GLenum pname, GLfloat* params);
 void glGetTexParameteriv (GLenum target, GLenum pname, GLint* params);
 void glGetUniformfv (GLuint program, GLint location, GLfloat* params);
 void glGetUniformiv (GLuint program, GLint location, GLint* params);
 int glGetUniformLocation (GLuint program, const GLchar* name);
 void glGetVertexAttribfv (GLuint index, GLenum pname, GLfloat* params);
 void glGetVertexAttribiv (GLuint index, GLenum pname, GLint* params);
 void glGetVertexAttribPointerv (GLuint index, GLenum pname, GLvoid** pointer);
 void glHint (GLenum target, GLenum mode);
 GLboolean glIsBuffer (GLuint buffer);
 GLboolean glIsEnabled (GLenum cap);
 GLboolean glIsFramebuffer (GLuint framebuffer);
 GLboolean glIsProgram (GLuint program);
 GLboolean glIsRenderbuffer (GLuint renderbuffer);
 GLboolean glIsShader (GLuint shader);
 GLboolean glIsTexture (GLuint texture);
 void glLineWidth (GLfloat width);
 void glLinkProgram (GLuint program);
 void glPixelStorei (GLenum pname, GLint param);
 void glPolygonOffset (GLfloat factor, GLfloat units);
 void glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* pixels);
 void glReleaseShaderCompiler (void);
 void glRenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
 void glSampleCoverage (GLclampf value, GLboolean invert);
 void glScissor (GLint x, GLint y, GLsizei width, GLsizei height);
 void glShaderBinary (GLsizei n, const GLuint* shaders, GLenum binaryformat, const GLvoid* binary, GLsizei length);
 void glShaderSource (GLuint shader, GLsizei count, const GLchar** string, const GLint* length);
 void glStencilFunc (GLenum func, GLint ref, GLuint mask);
 void glStencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask);
 void glStencilMask (GLuint mask);
 void glStencilMaskSeparate (GLenum face, GLuint mask);
 void glStencilOp (GLenum fail, GLenum zfail, GLenum zpass);
 void glStencilOpSeparate (GLenum face, GLenum fail, GLenum zfail, GLenum zpass);
 void glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid* pixels);
 void glTexParameterf (GLenum target, GLenum pname, GLfloat param);
 void glTexParameterfv (GLenum target, GLenum pname, const GLfloat* params);
 void glTexParameteri (GLenum target, GLenum pname, GLint param);
 void glTexParameteriv (GLenum target, GLenum pname, const GLint* params);
 void glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid* pixels);
 void glUniform1f (GLint location, GLfloat x);
 void glUniform1fv (GLint location, GLsizei count, const GLfloat* v);
 void glUniform1i (GLint location, GLint x);
 void glUniform1iv (GLint location, GLsizei count, const GLint* v);
 void glUniform2f (GLint location, GLfloat x, GLfloat y);
 void glUniform2fv (GLint location, GLsizei count, const GLfloat* v);
 void glUniform2i (GLint location, GLint x, GLint y);
 void glUniform2iv (GLint location, GLsizei count, const GLint* v);
 void glUniform3f (GLint location, GLfloat x, GLfloat y, GLfloat z);
 void glUniform3fv (GLint location, GLsizei count, const GLfloat* v);
 void glUniform3i (GLint location, GLint x, GLint y, GLint z);
 void glUniform3iv (GLint location, GLsizei count, const GLint* v);
 void glUniform4f (GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
 void glUniform4fv (GLint location, GLsizei count, const GLfloat* v);
 void glUniform4i (GLint location, GLint x, GLint y, GLint z, GLint w);
 void glUniform4iv (GLint location, GLsizei count, const GLint* v);
 void glUniformMatrix2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
 void glUniformMatrix3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
 void glUniformMatrix4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
 void glUseProgram (GLuint program);
 void glValidateProgram (GLuint program);
 void glVertexAttrib1f (GLuint indx, GLfloat x);
 void glVertexAttrib1fv (GLuint indx, const GLfloat* values);
 void glVertexAttrib2f (GLuint indx, GLfloat x, GLfloat y);
 void glVertexAttrib2fv (GLuint indx, const GLfloat* values);
 void glVertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z);
 void glVertexAttrib3fv (GLuint indx, const GLfloat* values);
 void glVertexAttrib4f (GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
 void glVertexAttrib4fv (GLuint indx, const GLfloat* values);
 void glVertexAttribPointer (GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid* ptr);
 void glViewport (GLint x, GLint y, GLsizei width, GLsizei height);
extern const GLenum _GL_ES_VERSION_2_0;
extern const GLenum _GL_DEPTH_BUFFER_BIT;
extern const GLenum _GL_STENCIL_BUFFER_BIT;
extern const GLenum _GL_COLOR_BUFFER_BIT;
extern const GLenum _GL_FALSE;
extern const GLenum _GL_TRUE;
extern const GLenum _GL_POINTS;
extern const GLenum _GL_LINES;
extern const GLenum _GL_LINE_LOOP;
extern const GLenum _GL_LINE_STRIP;
extern const GLenum _GL_TRIANGLES;
extern const GLenum _GL_TRIANGLE_STRIP;
extern const GLenum _GL_TRIANGLE_FAN;
extern const GLenum _GL_ZERO;
extern const GLenum _GL_ONE;
extern const GLenum _GL_SRC_COLOR;
extern const GLenum _GL_ONE_MINUS_SRC_COLOR;
extern const GLenum _GL_SRC_ALPHA;
extern const GLenum _GL_ONE_MINUS_SRC_ALPHA;
extern const GLenum _GL_DST_ALPHA;
extern const GLenum _GL_ONE_MINUS_DST_ALPHA;
extern const GLenum _GL_DST_COLOR;
extern const GLenum _GL_ONE_MINUS_DST_COLOR;
extern const GLenum _GL_SRC_ALPHA_SATURATE;
extern const GLenum _GL_FUNC_ADD;
extern const GLenum _GL_BLEND_EQUATION;
extern const GLenum _GL_BLEND_EQUATION_RGB;
extern const GLenum _GL_BLEND_EQUATION_ALPHA;
extern const GLenum _GL_FUNC_SUBTRACT;
extern const GLenum _GL_FUNC_REVERSE_SUBTRACT;
extern const GLenum _GL_BLEND_DST_RGB;
extern const GLenum _GL_BLEND_SRC_RGB;
extern const GLenum _GL_BLEND_DST_ALPHA;
extern const GLenum _GL_BLEND_SRC_ALPHA;
extern const GLenum _GL_CONSTANT_COLOR;
extern const GLenum _GL_ONE_MINUS_CONSTANT_COLOR;
extern const GLenum _GL_CONSTANT_ALPHA;
extern const GLenum _GL_ONE_MINUS_CONSTANT_ALPHA;
extern const GLenum _GL_BLEND_COLOR;
extern const GLenum _GL_ARRAY_BUFFER;
extern const GLenum _GL_ELEMENT_ARRAY_BUFFER;
extern const GLenum _GL_ARRAY_BUFFER_BINDING;
extern const GLenum _GL_ELEMENT_ARRAY_BUFFER_BINDING;
extern const GLenum _GL_STREAM_DRAW;
extern const GLenum _GL_STATIC_DRAW;
extern const GLenum _GL_DYNAMIC_DRAW;
extern const GLenum _GL_BUFFER_SIZE;
extern const GLenum _GL_BUFFER_USAGE;
extern const GLenum _GL_CURRENT_VERTEX_ATTRIB;
extern const GLenum _GL_FRONT;
extern const GLenum _GL_BACK;
extern const GLenum _GL_FRONT_AND_BACK;
extern const GLenum _GL_TEXTURE_2D;
extern const GLenum _GL_CULL_FACE;
extern const GLenum _GL_BLEND;
extern const GLenum _GL_DITHER;
extern const GLenum _GL_STENCIL_TEST;
extern const GLenum _GL_DEPTH_TEST;
extern const GLenum _GL_SCISSOR_TEST;
extern const GLenum _GL_POLYGON_OFFSET_FILL;
extern const GLenum _GL_SAMPLE_ALPHA_TO_COVERAGE;
extern const GLenum _GL_SAMPLE_COVERAGE;
extern const GLenum _GL_NO_ERROR;
extern const GLenum _GL_INVALID_ENUM;
extern const GLenum _GL_INVALID_VALUE;
extern const GLenum _GL_INVALID_OPERATION;
extern const GLenum _GL_OUT_OF_MEMORY;
extern const GLenum _GL_CW;
extern const GLenum _GL_CCW;
extern const GLenum _GL_LINE_WIDTH;
extern const GLenum _GL_ALIASED_POINT_SIZE_RANGE;
extern const GLenum _GL_ALIASED_LINE_WIDTH_RANGE;
extern const GLenum _GL_CULL_FACE_MODE;
extern const GLenum _GL_FRONT_FACE;
extern const GLenum _GL_DEPTH_RANGE;
extern const GLenum _GL_DEPTH_WRITEMASK;
extern const GLenum _GL_DEPTH_CLEAR_VALUE;
extern const GLenum _GL_DEPTH_FUNC;
extern const GLenum _GL_STENCIL_CLEAR_VALUE;
extern const GLenum _GL_STENCIL_FUNC;
extern const GLenum _GL_STENCIL_FAIL;
extern const GLenum _GL_STENCIL_PASS_DEPTH_FAIL;
extern const GLenum _GL_STENCIL_PASS_DEPTH_PASS;
extern const GLenum _GL_STENCIL_REF;
extern const GLenum _GL_STENCIL_VALUE_MASK;
extern const GLenum _GL_STENCIL_WRITEMASK;
extern const GLenum _GL_STENCIL_BACK_FUNC;
extern const GLenum _GL_STENCIL_BACK_FAIL;
extern const GLenum _GL_STENCIL_BACK_PASS_DEPTH_FAIL;
extern const GLenum _GL_STENCIL_BACK_PASS_DEPTH_PASS;
extern const GLenum _GL_STENCIL_BACK_REF;
extern const GLenum _GL_STENCIL_BACK_VALUE_MASK;
extern const GLenum _GL_STENCIL_BACK_WRITEMASK;
extern const GLenum _GL_VIEWPORT;
extern const GLenum _GL_SCISSOR_BOX;
extern const GLenum _GL_COLOR_CLEAR_VALUE;
extern const GLenum _GL_COLOR_WRITEMASK;
extern const GLenum _GL_UNPACK_ALIGNMENT;
extern const GLenum _GL_PACK_ALIGNMENT;
extern const GLenum _GL_MAX_TEXTURE_SIZE;
extern const GLenum _GL_MAX_VIEWPORT_DIMS;
extern const GLenum _GL_SUBPIXEL_BITS;
extern const GLenum _GL_RED_BITS;
extern const GLenum _GL_GREEN_BITS;
extern const GLenum _GL_BLUE_BITS;
extern const GLenum _GL_ALPHA_BITS;
extern const GLenum _GL_DEPTH_BITS;
extern const GLenum _GL_STENCIL_BITS;
extern const GLenum _GL_POLYGON_OFFSET_UNITS;
extern const GLenum _GL_POLYGON_OFFSET_FACTOR;
extern const GLenum _GL_TEXTURE_BINDING_2D;
extern const GLenum _GL_SAMPLE_BUFFERS;
extern const GLenum _GL_SAMPLES;
extern const GLenum _GL_SAMPLE_COVERAGE_VALUE;
extern const GLenum _GL_SAMPLE_COVERAGE_INVERT;
extern const GLenum _GL_NUM_COMPRESSED_TEXTURE_FORMATS;
extern const GLenum _GL_COMPRESSED_TEXTURE_FORMATS;
extern const GLenum _GL_DONT_CARE;
extern const GLenum _GL_FASTEST;
extern const GLenum _GL_NICEST;
extern const GLenum _GL_GENERATE_MIPMAP_HINT;
extern const GLenum _GL_BYTE;
extern const GLenum _GL_UNSIGNED_BYTE;
extern const GLenum _GL_SHORT;
extern const GLenum _GL_UNSIGNED_SHORT;
extern const GLenum _GL_INT;
extern const GLenum _GL_UNSIGNED_INT;
extern const GLenum _GL_FLOAT;
extern const GLenum _GL_FIXED;
extern const GLenum _GL_DEPTH_COMPONENT;
extern const GLenum _GL_ALPHA;
extern const GLenum _GL_RGB;
extern const GLenum _GL_RGBA;
extern const GLenum _GL_LUMINANCE;
extern const GLenum _GL_LUMINANCE_ALPHA;
extern const GLenum _GL_UNSIGNED_SHORT_4_4_4_4;
extern const GLenum _GL_UNSIGNED_SHORT_5_5_5_1;
extern const GLenum _GL_UNSIGNED_SHORT_5_6_5;
extern const GLenum _GL_FRAGMENT_SHADER;
extern const GLenum _GL_VERTEX_SHADER;
extern const GLenum _GL_MAX_VERTEX_ATTRIBS;
extern const GLenum _GL_MAX_VERTEX_UNIFORM_VECTORS;
extern const GLenum _GL_MAX_VARYING_VECTORS;
extern const GLenum _GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS;
extern const GLenum _GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS;
extern const GLenum _GL_MAX_TEXTURE_IMAGE_UNITS;
extern const GLenum _GL_MAX_FRAGMENT_UNIFORM_VECTORS;
extern const GLenum _GL_SHADER_TYPE;
extern const GLenum _GL_DELETE_STATUS;
extern const GLenum _GL_LINK_STATUS;
extern const GLenum _GL_VALIDATE_STATUS;
extern const GLenum _GL_ATTACHED_SHADERS;
extern const GLenum _GL_ACTIVE_UNIFORMS;
extern const GLenum _GL_ACTIVE_UNIFORM_MAX_LENGTH;
extern const GLenum _GL_ACTIVE_ATTRIBUTES;
extern const GLenum _GL_ACTIVE_ATTRIBUTE_MAX_LENGTH;
extern const GLenum _GL_SHADING_LANGUAGE_VERSION;
extern const GLenum _GL_CURRENT_PROGRAM;
extern const GLenum _GL_NEVER;
extern const GLenum _GL_LESS;
extern const GLenum _GL_EQUAL;
extern const GLenum _GL_LEQUAL;
extern const GLenum _GL_GREATER;
extern const GLenum _GL_NOTEQUAL;
extern const GLenum _GL_GEQUAL;
extern const GLenum _GL_ALWAYS;
extern const GLenum _GL_KEEP;
extern const GLenum _GL_REPLACE;
extern const GLenum _GL_INCR;
extern const GLenum _GL_DECR;
extern const GLenum _GL_INVERT;
extern const GLenum _GL_INCR_WRAP;
extern const GLenum _GL_DECR_WRAP;
extern const GLenum _GL_VENDOR;
extern const GLenum _GL_RENDERER;
extern const GLenum _GL_VERSION;
extern const GLenum _GL_EXTENSIONS;
extern const GLenum _GL_NEAREST;
extern const GLenum _GL_LINEAR;
extern const GLenum _GL_NEAREST_MIPMAP_NEAREST;
extern const GLenum _GL_LINEAR_MIPMAP_NEAREST;
extern const GLenum _GL_NEAREST_MIPMAP_LINEAR;
extern const GLenum _GL_LINEAR_MIPMAP_LINEAR;
extern const GLenum _GL_TEXTURE_MAG_FILTER;
extern const GLenum _GL_TEXTURE_MIN_FILTER;
extern const GLenum _GL_TEXTURE_WRAP_S;
extern const GLenum _GL_TEXTURE_WRAP_T;
extern const GLenum _GL_TEXTURE;
extern const GLenum _GL_TEXTURE_CUBE_MAP;
extern const GLenum _GL_TEXTURE_BINDING_CUBE_MAP;
extern const GLenum _GL_TEXTURE_CUBE_MAP_POSITIVE_X;
extern const GLenum _GL_TEXTURE_CUBE_MAP_NEGATIVE_X;
extern const GLenum _GL_TEXTURE_CUBE_MAP_POSITIVE_Y;
extern const GLenum _GL_TEXTURE_CUBE_MAP_NEGATIVE_Y;
extern const GLenum _GL_TEXTURE_CUBE_MAP_POSITIVE_Z;
extern const GLenum _GL_TEXTURE_CUBE_MAP_NEGATIVE_Z;
extern const GLenum _GL_MAX_CUBE_MAP_TEXTURE_SIZE;
extern const GLenum _GL_TEXTURE0;
extern const GLenum _GL_TEXTURE1;
extern const GLenum _GL_TEXTURE2;
extern const GLenum _GL_TEXTURE3;
extern const GLenum _GL_TEXTURE4;
extern const GLenum _GL_TEXTURE5;
extern const GLenum _GL_TEXTURE6;
extern const GLenum _GL_TEXTURE7;
extern const GLenum _GL_TEXTURE8;
extern const GLenum _GL_TEXTURE9;
extern const GLenum _GL_TEXTURE10;
extern const GLenum _GL_TEXTURE11;
extern const GLenum _GL_TEXTURE12;
extern const GLenum _GL_TEXTURE13;
extern const GLenum _GL_TEXTURE14;
extern const GLenum _GL_TEXTURE15;
extern const GLenum _GL_TEXTURE16;
extern const GLenum _GL_TEXTURE17;
extern const GLenum _GL_TEXTURE18;
extern const GLenum _GL_TEXTURE19;
extern const GLenum _GL_TEXTURE20;
extern const GLenum _GL_TEXTURE21;
extern const GLenum _GL_TEXTURE22;
extern const GLenum _GL_TEXTURE23;
extern const GLenum _GL_TEXTURE24;
extern const GLenum _GL_TEXTURE25;
extern const GLenum _GL_TEXTURE26;
extern const GLenum _GL_TEXTURE27;
extern const GLenum _GL_TEXTURE28;
extern const GLenum _GL_TEXTURE29;
extern const GLenum _GL_TEXTURE30;
extern const GLenum _GL_TEXTURE31;
extern const GLenum _GL_ACTIVE_TEXTURE;
extern const GLenum _GL_REPEAT;
extern const GLenum _GL_CLAMP_TO_EDGE;
extern const GLenum _GL_MIRRORED_REPEAT;
extern const GLenum _GL_FLOAT_VEC2;
extern const GLenum _GL_FLOAT_VEC3;
extern const GLenum _GL_FLOAT_VEC4;
extern const GLenum _GL_INT_VEC2;
extern const GLenum _GL_INT_VEC3;
extern const GLenum _GL_INT_VEC4;
extern const GLenum _GL_BOOL;
extern const GLenum _GL_BOOL_VEC2;
extern const GLenum _GL_BOOL_VEC3;
extern const GLenum _GL_BOOL_VEC4;
extern const GLenum _GL_FLOAT_MAT2;
extern const GLenum _GL_FLOAT_MAT3;
extern const GLenum _GL_FLOAT_MAT4;
extern const GLenum _GL_SAMPLER_2D;
extern const GLenum _GL_SAMPLER_CUBE;
extern const GLenum _GL_VERTEX_ATTRIB_ARRAY_ENABLED;
extern const GLenum _GL_VERTEX_ATTRIB_ARRAY_SIZE;
extern const GLenum _GL_VERTEX_ATTRIB_ARRAY_STRIDE;
extern const GLenum _GL_VERTEX_ATTRIB_ARRAY_TYPE;
extern const GLenum _GL_VERTEX_ATTRIB_ARRAY_NORMALIZED;
extern const GLenum _GL_VERTEX_ATTRIB_ARRAY_POINTER;
extern const GLenum _GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING;
extern const GLenum _GL_IMPLEMENTATION_COLOR_READ_TYPE;
extern const GLenum _GL_IMPLEMENTATION_COLOR_READ_FORMAT;
extern const GLenum _GL_COMPILE_STATUS;
extern const GLenum _GL_INFO_LOG_LENGTH;
extern const GLenum _GL_SHADER_SOURCE_LENGTH;
extern const GLenum _GL_SHADER_COMPILER;
extern const GLenum _GL_SHADER_BINARY_FORMATS;
extern const GLenum _GL_NUM_SHADER_BINARY_FORMATS;
extern const GLenum _GL_LOW_FLOAT;
extern const GLenum _GL_MEDIUM_FLOAT;
extern const GLenum _GL_HIGH_FLOAT;
extern const GLenum _GL_LOW_INT;
extern const GLenum _GL_MEDIUM_INT;
extern const GLenum _GL_HIGH_INT;
extern const GLenum _GL_FRAMEBUFFER;
extern const GLenum _GL_RENDERBUFFER;
extern const GLenum _GL_RGBA4;
extern const GLenum _GL_RGB5_A1;
extern const GLenum _GL_RGB565;
extern const GLenum _GL_DEPTH_COMPONENT16;
extern const GLenum _GL_STENCIL_INDEX;
extern const GLenum _GL_STENCIL_INDEX8;
extern const GLenum _GL_RENDERBUFFER_WIDTH;
extern const GLenum _GL_RENDERBUFFER_HEIGHT;
extern const GLenum _GL_RENDERBUFFER_INTERNAL_FORMAT;
extern const GLenum _GL_RENDERBUFFER_RED_SIZE;
extern const GLenum _GL_RENDERBUFFER_GREEN_SIZE;
extern const GLenum _GL_RENDERBUFFER_BLUE_SIZE;
extern const GLenum _GL_RENDERBUFFER_ALPHA_SIZE;
extern const GLenum _GL_RENDERBUFFER_DEPTH_SIZE;
extern const GLenum _GL_RENDERBUFFER_STENCIL_SIZE;
extern const GLenum _GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE;
extern const GLenum _GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME;
extern const GLenum _GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL;
extern const GLenum _GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE;
extern const GLenum _GL_COLOR_ATTACHMENT0;
extern const GLenum _GL_DEPTH_ATTACHMENT;
extern const GLenum _GL_STENCIL_ATTACHMENT;
extern const GLenum _GL_NONE;
extern const GLenum _GL_FRAMEBUFFER_COMPLETE;
extern const GLenum _GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT;
extern const GLenum _GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT;
extern const GLenum _GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS;
extern const GLenum _GL_FRAMEBUFFER_UNSUPPORTED;
extern const GLenum _GL_FRAMEBUFFER_BINDING;
extern const GLenum _GL_RENDERBUFFER_BINDING;
extern const GLenum _GL_MAX_RENDERBUFFER_SIZE;
extern const GLenum _GL_INVALID_FRAMEBUFFER_OPERATION;
